#spring:
#  datasource:
#    username: root
#    password: password
#    url: jdbc:mysql://localhost:3306/phonedb
#    drive-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
